apiVersion: ENC[AES256_GCM,data:kpM=,iv:Mo+IUq1+2/hmu0UlzVU7x6OwBh3RKUlMFebfPzCANFU=,tag:TOjbHJn98uZMF46mdJQFng==,type:str]
kind: ENC[AES256_GCM,data:eMpnEF6d,iv:neZmbLY9GAfKNlFZDq6GWmB+YiM9Vt/Hd9r0NGvAEvI=,tag:Ur9DmpYpBRYo7cEU8hFl2Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kJ2XcdYoA5Src+XCYVjo,iv:9SErtWKji8zvX7imIOSD5uLm/vXxE1m3POubQJKwUpY=,tag:zLQrKJPSGRMm8PIWwgn0mQ==,type:str]
    namespace: ENC[AES256_GCM,data:G9ygbjT8tvhzpmU=,iv:Qvq4vcnqdcLQQ8xfkc8w5wNKvEUddeIL+TZaCefYwnA=,tag:6ie6v+C913latG4G1mKkzw==,type:str]
type: ENC[AES256_GCM,data:VU7yWpyV,iv:TjERHdIE0Vo3VHERv31dUgz3er8kKzRemEXgFGr9ANg=,tag:je1BnLLkhwLdAqA7lgrqLw==,type:str]
#ENC[AES256_GCM,data:XVi5hHEETAz3CVYJiD2AmaalxzJGY8mZYkC3OrWU2EQ2ILHB4wbCRiJTp5suhKr6vSrR9dkocWedelOYeebu,iv:0KgY7GqO1n5iK5gD5eg4V1dP7aujn9dvhbhBe10jcbM=,tag:7NzX8tvpy3WVuRX50oLFmQ==,type:comment]
data:
    IMAP_USER: ENC[AES256_GCM,data:lY3IC/7o87e91jzEKK6ymHeqKUR6JGeSxl4m8Q==,iv:WQmHa26LHcaPmY0BHjWCghT7a/z6hS+d/z+gdefqGBM=,tag:JcBNZ8czL6S9fl3coDEbXQ==,type:str]
    IMAP_PASSWORD: ENC[AES256_GCM,data:af83AGluKLQ2WRDGb10JScuFZBPK5IXf,iv:63UyI6Bt4d2xmWvaLzoFjJDP4Yj8TfJpt0keqPjNThY=,tag:uFvVPi4v01kHkTLz6QXu5w==,type:str]
    NTFY_TOKEN: ENC[AES256_GCM,data:vKUalE4Scs0ubOl1YaBWkrlk/l2jIXNI96ijdYy8bqLTf+LIbfXE6//GqPw=,iv:x+KwuOxPMqaizSERJduyuoTTx+PM06w4pYbzkeMohRM=,tag:f+Vt/lUsTnwEUWr0oVrv4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReWc3MlFZQnh2UGpjNk1k
            Q0FHVG84YXRMc1pTZnpGN2lSTlp5TWh0MGxvClM4MGxDUHowa1dnWS9jM21oU3FO
            UExDalNrWkVKM1lkaDFmTUUwMXdGa2cKLS0tIGdEV3FvSHBycXM1WEpxeXdVd0RN
            dEdqOHlVdUgreFNNRUFEc281U1owZ1kK0vAQfJi7FUEKeW8A0IPyLkZP6UNNmQCb
            HjhsBWg/b237HOMQBW1Th+F/9WTwXnh0j1L1CFIt+wpBIMsoqTtRiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl0nmje9vetdgudflgcnnydcg44kv9a5px4e8lhyaz3qfqewjfhqhdg5ra
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eThLRjVQalg1dzZoQ3Q2
            dlRUWUtxeFlpK2UySUpDUGpMMjljc0dwcVVBCk5KaEpuNnVPZklFbTRWZEl6MUxj
            Ry9jU2JIdEI0eU5ZT0l6WCtsRmxWL1EKLS0tIDlxSlprekh5OXc1R3hJR09lcXJl
            WVBBT1dSaHFKZHpINHlEYThGbE9ybDAKm96OyldW4G7UiXO2ZA4+Ajs83dG351fp
            leqqx82sz/bRGVDkbCtEf7fzmff87IHYUlydGkruUw9B04Re6arFxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pxc3l7nck3ku25nd66f5ul0c0gkhtnjmnr3zk0ftmm2yt3qn0q8strdzdy
    lastmodified: "2026-09-29T14:02:31Z"
    mac: ENC[AES256_GCM,data:l7YZEgF5vOJRScUJmQPTIljLUFzkvldCmBQOtRZJnKy0Vt79oiYvDepc6ABvglTpUveoQf3iOsLaMGxShjG31MR97szQDC9VivPJYKOdJwSbxrmzrXbZHGTjC5JxGptaiHt2ze+RqM7zwDmk2bkm4UI2DCaogIec1iFzBWJi2s4=,iv:J21CKRYjkoxJEQSTwOPds4cIrr9IZysXRNrWBIr9RZ4=,tag:2ZBooQH2i3hIg24qov50Zw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
---
apiVersion: ENC[AES256_GCM,data:4Gc=,iv:3idaz+YT4Smf9RBlS7OXgNX8WavQ5jiow+hkMGebxs8=,tag:fwcJeAK574XHqh7I5x/ocg==,type:str]
kind: ENC[AES256_GCM,data:l1d/Pp69,iv:fPJTVjy2qkMeEprAj5YDqRWj6mnv66W1mJEfgNulSzc=,tag:oWcJDmsxHfVLHN/jmFX4IA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YYYFEvi7Ie6rrU1/AA==,iv:HjhNkNNms4NKpDUAESqrQBmPXxsNQz9CaMs2LfvM/Qo=,tag:jpSoWMjA2r+SRutyk7Vs7A==,type:str]
    namespace: ENC[AES256_GCM,data:yfQEezhVZ+6u6Ww=,iv:PlAFIyPejTj0Ncfnl4CdW17/TDMb6xQrLojLe74OHWk=,tag:IbP/STtet6gnxEVi5Am3Zw==,type:str]
type: ENC[AES256_GCM,data:MlkkqfNBzBKDGCPXlqKLj1u9Se0IiqEiQTnNMroQ,iv:wX8tfA72K/GgwEn+7ON7TURtFcqy7t/9wUZUunXsfzs=,tag:knRLbyDdjVLiUvLSicnVlw==,type:str]
data:
    .dockerconfigjson: ENC[AES256_GCM,data:VbH63lhfprILPUbpjsvQ7eT9vDft3JmUtUnrOZhpeQlhpZZ581SUQWgKt33BUSZ43GDx0qjsf5t8Y3BGdZpOlcgqxWaU/t3upF+1FMafpQRyVbyMfNp/m7D0nmoceRhDUGlxj2oq7noZmxEFVDNeG7XkDMccJlQqRemCUYSH/7bezFm2I0QIBiw550VMbJTBj7zoIrcLv6l4sTEBE8Yj/XqjVPk8PgwRUMYQvf9SVImWuK9C1no4Db/2ngDYSby/Rl51FvYwmi7uaYxcIXSHOU6FWi5g+qUAEvxPVvLQFkf1VSIiyajjzsWqwK/qflvgGTnboxBZnwIDS8GjWB/4TQUt/6bX1KkGUhkz2RxHXLYyeTEVTlZXxp7NIK+l8DvufV5jLCvo/L7/6P0l5SxlyHKFuhBYbgdFzeNRunEQhXp8Ctm2pw2Jjg==,iv:VaWkaCUuuVTpEiRTf4CJG9HoeZsdtljF010RFVkTIgk=,tag:CX+89qmo8MPWbx8XoZ3Tcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReWc3MlFZQnh2UGpjNk1k
            Q0FHVG84YXRMc1pTZnpGN2lSTlp5TWh0MGxvClM4MGxDUHowa1dnWS9jM21oU3FO
            UExDalNrWkVKM1lkaDFmTUUwMXdGa2cKLS0tIGdEV3FvSHBycXM1WEpxeXdVd0RN
            dEdqOHlVdUgreFNNRUFEc281U1owZ1kK0vAQfJi7FUEKeW8A0IPyLkZP6UNNmQCb
            HjhsBWg/b237HOMQBW1Th+F/9WTwXnh0j1L1CFIt+wpBIMsoqTtRiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl0nmje9vetdgudflgcnnydcg44kv9a5px4e8lhyaz3qfqewjfhqhdg5ra
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eThLRjVQalg1dzZoQ3Q2
            dlRUWUtxeFlpK2UySUpDUGpMMjljc0dwcVVBCk5KaEpuNnVPZklFbTRWZEl6MUxj
            Ry9jU2JIdEI0eU5ZT0l6WCtsRmxWL1EKLS0tIDlxSlprekh5OXc1R3hJR09lcXJl
            WVBBT1dSaHFKZHpINHlEYThGbE9ybDAKm96OyldW4G7UiXO2ZA4+Ajs83dG351fp
            leqqx82sz/bRGVDkbCtEf7fzmff87IHYUlydGkruUw9B04Re6arFxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pxc3l7nck3ku25nd66f5ul0c0gkhtnjmnr3zk0ftmm2yt3qn0q8strdzdy
    lastmodified: "2026-09-29T14:02:31Z"
    mac: ENC[AES256_GCM,data:l7YZEgF5vOJRScUJmQPTIljLUFzkvldCmBQOtRZJnKy0Vt79oiYvDepc6ABvglTpUveoQf3iOsLaMGxShjG31MR97szQDC9VivPJYKOdJwSbxrmzrXbZHGTjC5JxGptaiHt2ze+RqM7zwDmk2bkm4UI2DCaogIec1iFzBWJi2s4=,iv:J21CKRYjkoxJEQSTwOPds4cIrr9IZysXRNrWBIr9RZ4=,tag:2ZBooQH2i3hIg24qov50Zw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
