apiVersion: ENC[AES256_GCM,data:BF4=,iv:f2oF1sHWqqlzPZSlMHMaguOirXM9HHTw/toivXre98o=,tag:DmxXwSKDvFVb9sitgpRcrw==,type:str]
kind: ENC[AES256_GCM,data:aWZi0d6T,iv:4ZWE0gTs4hL1FmxeP+7FI9OoBxZEC2WxiDPKQR3xHto=,tag:E2KOhKlN/cvgohZWl0Qz6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KgltsZXW21GQvw==,iv:MUVGgQ9253TWEvIl4G2DD9qsfo+r8jD1/J3aj8JPpe8=,tag:j5hdwv4WHT+7YSb34/cxIw==,type:str]
    namespace: ENC[AES256_GCM,data:4NVB6CXl,iv:q58FBFAxSsB6ZkJZpO7hEEDvt/S+jMY/oFiNzQbfXHg=,tag:OCLawsRkjDNc0oPT6snmVA==,type:str]
type: ENC[AES256_GCM,data:cDZn7ekN,iv:cohi8rBzM+llN9W29fWBq/zq0bl89RvXMuK4/n8KtWY=,tag:DjizXqfG6qGH8aw6vagMEA==,type:str]
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:rmvuxow3cULnK2XRI52cpHVGGEX/RenszCT/i/VkWyrUZFuq6cyDZh9nLJwpS+78HfmI6uNQUw/+hqKyrbFQ33Cj+V9lyKDTC+I2dTIWlsszLdbdRA75zcoc8r4wepBYIzZxzW59tDEsZwWLWqf+gxgZ12ohdL5GYhPqY7WA1rQ=,iv:SpRRmVz5f4IWSRCLCi23M00Aqp8IvGUJR+hJ4SS2peQ=,tag:BuPsANtSRUANkGggDKZb3Q==,type:str]
    MEALIE_API_TOKEN: ENC[AES256_GCM,data:BOlz571JUAd7+R+tTjrgqfmkJq9FIGYwrZWHvciJWUM+JdXVAAT7gudu2sPJ0zYXenE7I01s704rkihBgPgbxNcvcxnBy16CIgjCp4L4f7q68H0EAtX2QXMBclaagho6BW6ogPoPrdU+5gUvFHmyRs2p+EGnychi9aCBKknB4GUw7o6wHP66Nz7UNJIVhZJbwPBGfkuwOnssMHIDPSIGp92qskU4o0Hp0PiFPe5bP2NxtfSmApSCdrgmVkk5Bhr0ISJOIfPsRRuMwTVNQikZBiVtzwPSdwALOCE/dk7fgvlmmUIAxsQk0jeunbEXlsycSkrCx+FZQxGkXy+ZEN9uA0d+6kPW1fgrLw==,iv:XWWtbrcTO+gRNsh3Qj7cf/yvFDPVYrknMsRSgUY3AwY=,tag:Sxq/36EjUKhkBiXP5UThuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZFJYWVlmZGVRN2dCRXA3
            Z1R1Y0VJNVN5cjNOdmxXRldpTlZGMEMzZlJNCm4welR3YWI1K2djVmZDZ2thRXAw
            bC9HTGdweG1HWENpdE5aZ08yRFlYOUkKLS0tIG1oYm1UeGRhdjVUbFQvUE9vZ3dt
            cGtiNUxVOGp5QWtnR0pUdnlaTlJvZncKpIiAAK8MnpojKXXMJ258rRpQVcMA2jpY
            J1Hp6LTGfFyiSbtm70y1cvO/KTJwJLx0UNMO7cEB/FfKW+K8Qc7Jtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl0nmje9vetdgudflgcnnydcg44kv9a5px4e8lhyaz3qfqewjfhqhdg5ra
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdVZpT2QxM1N4S2JianVB
            RURqVWpSL0RkNGhCOGI2SGtXZlA3dEt6WUNJCmJJNFp2RUFpdk03b1ZtSGlCL1Bt
            aWVJQWg5Y0FYL0o1L1lzZXVzaUhtQ1kKLS0tIHcvWGh6UXVmV3ZLSllGcDIxbStL
            MnVxZ3hmaUUra2Vnd1N5UFFjcGxvaEUKehrW8sKTn8E1R9D/zcq61Zq4Tulozf3J
            kvGjZeLaEzjgrgCHisWXm1cpFjPoh+o7+UYbPqTPbZVRd96j0tDeWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pxc3l7nck3ku25nd66f5ul0c0gkhtnjmnr3zk0ftmm2yt3qn0q8strdzdy
    lastmodified: "2026-08-04T16:16:39Z"
    mac: ENC[AES256_GCM,data:ZdRUz59pJhgLZMUNDVhdXQseSLZ/AYj4ZelgQjF0lpTP+/bK0mtg5BEi9nUhILDaNKWiwXi7luxJIEBtf315+h2aK30jbdTkBn84NLtPiim8ADvfo9+q8CR3q5kMMB3C8468EYNDNzhnbBDnw1vCNJ1/ePrGkbuweZIf/+LBg/U=,iv:RqwuC4v0snBfOfFfj3sBgqGIYh2Yk1zCTAkOJP+8PDw=,tag:+NYV/pHVogycwL31KPBU7A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
