apiVersion: ENC[AES256_GCM,data:BF4=,iv:f2oF1sHWqqlzPZSlMHMaguOirXM9HHTw/toivXre98o=,tag:DmxXwSKDvFVb9sitgpRcrw==,type:str]
kind: ENC[AES256_GCM,data:aWZi0d6T,iv:4ZWE0gTs4hL1FmxeP+7FI9OoBxZEC2WxiDPKQR3xHto=,tag:E2KOhKlN/cvgohZWl0Qz6Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KgltsZXW21GQvw==,iv:MUVGgQ9253TWEvIl4G2DD9qsfo+r8jD1/J3aj8JPpe8=,tag:j5hdwv4WHT+7YSb34/cxIw==,type:str]
    namespace: ENC[AES256_GCM,data:4NVB6CXl,iv:q58FBFAxSsB6ZkJZpO7hEEDvt/S+jMY/oFiNzQbfXHg=,tag:OCLawsRkjDNc0oPT6snmVA==,type:str]
type: ENC[AES256_GCM,data:cDZn7ekN,iv:cohi8rBzM+llN9W29fWBq/zq0bl89RvXMuK4/n8KtWY=,tag:DjizXqfG6qGH8aw6vagMEA==,type:str]
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:7g6RAMDod2xNkLVUATgRPCfvZbfmfPiasJmvUE4/yedbmxkPvm32Id3hcBoywtGqT5lIwz8lgFRymNZZkkxCifhKzwCmWe8ukuiAZeFZwSKrDcX5grNvh5kFzBFuMoOfgiOHSFhILVBOYMrj6ciMH+Z8zowxsezk,iv:F5kAxMavfkUHcF0RYwrr5wsXphH5LxMWJ3q6aqOAPdM=,tag:qK2Ms8isODqAPSdWh/BJMg==,type:str]
    MEALIE_API_TOKEN: ENC[AES256_GCM,data:BOlz571JUAd7+R+tTjrgqfmkJq9FIGYwrZWHvciJWUM+JdXVAAT7gudu2sPJ0zYXenE7I01s704rkihBgPgbxNcvcxnBy16CIgjCp4L4f7q68H0EAtX2QXMBclaagho6BW6ogPoPrdU+5gUvFHmyRs2p+EGnychi9aCBKknB4GUw7o6wHP66Nz7UNJIVhZJbwPBGfkuwOnssMHIDPSIGp92qskU4o0Hp0PiFPe5bP2NxtfSmApSCdrgmVkk5Bhr0ISJOIfPsRRuMwTVNQikZBiVtzwPSdwALOCE/dk7fgvlmmUIAxsQk0jeunbEXlsycSkrCx+FZQxGkXy+ZEN9uA0d+6kPW1fgrLw==,iv:XWWtbrcTO+gRNsh3Qj7cf/yvFDPVYrknMsRSgUY3AwY=,tag:Sxq/36EjUKhkBiXP5UThuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZFJYWVlmZGVRN2dCRXA3
            Z1R1Y0VJNVN5cjNOdmxXRldpTlZGMEMzZlJNCm4welR3YWI1K2djVmZDZ2thRXAw
            bC9HTGdweG1HWENpdE5aZ08yRFlYOUkKLS0tIG1oYm1UeGRhdjVUbFQvUE9vZ3dt
            cGtiNUxVOGp5QWtnR0pUdnlaTlJvZncKpIiAAK8MnpojKXXMJ258rRpQVcMA2jpY
            J1Hp6LTGfFyiSbtm70y1cvO/KTJwJLx0UNMO7cEB/FfKW+K8Qc7Jtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl0nmje9vetdgudflgcnnydcg44kv9a5px4e8lhyaz3qfqewjfhqhdg5ra
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdVZpT2QxM1N4S2JianVB
            RURqVWpSL0RkNGhCOGI2SGtXZlA3dEt6WUNJCmJJNFp2RUFpdk03b1ZtSGlCL1Bt
            aWVJQWg5Y0FYL0o1L1lzZXVzaUhtQ1kKLS0tIHcvWGh6UXVmV3ZLSllGcDIxbStL
            MnVxZ3hmaUUra2Vnd1N5UFFjcGxvaEUKehrW8sKTn8E1R9D/zcq61Zq4Tulozf3J
            kvGjZeLaEzjgrgCHisWXm1cpFjPoh+o7+UYbPqTPbZVRd96j0tDeWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pxc3l7nck3ku25nd66f5ul0c0gkhtnjmnr3zk0ftmm2yt3qn0q8strdzdy
    lastmodified: "2026-08-04T14:48:51Z"
    mac: ENC[AES256_GCM,data:x18mzYgkrnLwMARpkXuPi816Dz2L16lmhZL8Ny5eCaaXXBg4uPOJqw4idFU1uDkW6twpEwO3hiNONnTgGmWmpgNQuzMF5jimMu87m+7v2Qtuet18mDQ+RQdQaGsTRghdC1mdKmsiAFH8QftCORbXBdC2fA2VlbwrXuqna78d3Oo=,iv:Ff9MD/p1yLdWtU95H+9CgEDM7ygrxQZzM6TVAr2Hcw0=,tag:FPmdTrOMJgL+9FTuLJzFMQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
