server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.10.40.20:3100/loki/api/v1/push

scrape_configs:

# System logs
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: system
      host: tatooine
      __path__: /var/log/*.log

# Auth logs (SSH, sudo)
- job_name: auth
  static_configs:
  - targets:
      - localhost
    labels:
      job: auth
      host: tatooine
      __path__: /var/log/auth.log

# Docker container logs
- job_name: docker
  pipeline_stages:
    - docker: {}
    - json:
        expressions:
          stream: stream
          time: time
    - labels:
        stream:
    - timestamp:
        source: time
        format: RFC3339Nano
  static_configs:
    - targets:
        - localhost
      labels:
        job: docker
        host: tatooine
        __path__: /var/lib/docker/containers/*/*-json.log