---
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: "always"
    privileged: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/serial/by-id/usb-Nabu_Casa_SkyConnect_v1.0_7e0bb9507518ec11b1a4af9347486eb0-if00-port0:/dev/zigbee
      - /dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_550373132373514142B0-if00:/dev/arduino
    network_mode: host

  appdaemon:
    image: acockburn/appdaemon:latest
    container_name: appdaemon
    environment:
      HA_URL: "http://${SERVER_IP}:8123"
      TOKEN: "${HA_APPDAEMON_KEY}"
      DASH_URL: "http://${SERVER_IP}:5050"
    volumes:
      - ./config/appdaemon:/conf
    depends_on:
      - homeassistant
    restart: "always"
    network_mode: host

  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - ./esphome-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    ports:
      - "6052:6052"

networks:
  proxy:
    external: true
