apiVersion: ENC[AES256_GCM,data:RK4=,iv:Gpsxup8yEukEpoAWahV7afxnsHWFOnT867wB3B/5wR8=,tag:bB7FCgFk8oS1R0Tsq1TRyw==,type:str]
kind: ENC[AES256_GCM,data:uZ2n9dcN,iv:3jAn63ybUOJEB/neMt+dxfGcuiaUpFTd5A53d4WTh6M=,tag:TAK9w/KQKzLrEujHRzHVgA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:MRlRbsneEVzu,iv:+SGlTA3vQpiRZWSr0hmw14FHLmRdhp6mQCBCc5upkzI=,tag:myKTlxPRh3VAOs/s8RI1OQ==,type:str]
    namespace: ENC[AES256_GCM,data:W6RlqsI=,iv:CZKG373MRUj+lErBFPjX/tlUnVlzErDU2BksNUM7pr4=,tag:R7R0JdN13ohJ5u1NILVJig==,type:str]
stringData:
    MONGO_USER: ENC[AES256_GCM,data:4LqXvKPM,iv:btBJcOCSGgjZf5Iha2HcK2VMrHG9VKK5PSsqWtKbwsc=,tag:1gbHMvfl4sW07BHzSRARwQ==,type:str]
    MONGO_PASS: ENC[AES256_GCM,data:UGer8USc6D+dnMhdAy44FbKF2Lv8lEy9bvb+c4hN1g==,iv:rsAhaBDGR335mGWeCPQ1RvtVDkOpNbfQSxWx5FkTCfA=,tag:p0qfI36Cn2lln6OndyobVg==,type:str]
    MONGO_HOST: ENC[AES256_GCM,data:3HKGyO6Em5SqEx0=,iv:YMkd5lRRwxFpX70hhJmZAIcUcMS3f2kg3SfNBxVsPHw=,tag:lrrAJR/ol2j+j4YsMGV8vQ==,type:str]
    MONGO_PORT: ENC[AES256_GCM,data:KLQ+Ud0=,iv:Y3lKVR+htm3bmby/zc/NiQan2mi+hH8XkRujQdpRaYc=,tag:24HAWYvrqOjly79ZAN8sPw==,type:str]
    MONGO_DBNAME: ENC[AES256_GCM,data:DIuxiPg=,iv:3YQqakjYPJVq71gJXAaqHk9PR2qC3R3k95nzOoE7e8Y=,tag:RG6RyWPZrUOM1t+0X03l/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aStueXVteWJ0em1Qbm5w
            MkRvMFJGdkdBVkFTWnZSR3lrL0dKZ3EvQ1VjCjllTmVxc0xmelNCNDQ2MzFDNjhv
            dWFMZ2djdHRwUW1tNXhnNjFvRWgrNlEKLS0tIDBFZWkwdm5QLyt4d21jUzgrUmd3
            ZVNYcWRNVkExQktCaXdDWG9ZVDRJQTgK1/bxp7qT/AnQmPgTPnq+vO1daxUfQLMY
            81sPLVrEo6UMjOVE4WxzzFXnUPPFoPDdbsjTGIhMaN08l82citYhig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl0nmje9vetdgudflgcnnydcg44kv9a5px4e8lhyaz3qfqewjfhqhdg5ra
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQnkydXZlbTc4empkckxJ
            eEJNNHVEVmI5cE9ET1RKKy90a1A2dnJmRVFNCjBOMlFTSUpvdVZhUzNTdFhBRm5u
            czhhc3JyRmxNam9QSzZkS0ZUMGhGUzgKLS0tIEFYTnRkQ2RaeGU0Q05pc2NVNWhm
            OVYzbS9SVzI3cUJTRXlGWW9aQ2h0emsKJ+IVQl0PR0SJ5gRJZDEYWfXHYbU2uyNV
            uZWtFU3bo+s6/4Cm4tuK8HRzvbnoM9BzK6PUB25V2IhsBalNUagUEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pxc3l7nck3ku25nd66f5ul0c0gkhtnjmnr3zk0ftmm2yt3qn0q8strdzdy
    lastmodified: "2026-07-06T12:07:08Z"
    mac: ENC[AES256_GCM,data:u1y+X+GAmRT+VbRyHfSIhpSaQ/PKtoACiVMxAluMsxJ4ShSM1MkTY7W4E5aoiXMbUltqMrGNCJ4JBs9EEZQp4YUpDjQqOzNpo5Rw9IbEHy+UW32FxTToRHfyyvqNukFm5SQS7LNBB6Gn9glwmB9j0dpDbnbAMlOeB/zJH+skryg=,iv:kcWhnMYW5xinaUCP52jrOaN/9rG0H1g+N6q//jcWSsk=,tag:+sZftkAHsAwKKSvloCi/+A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
