apiVersion: ENC[AES256_GCM,data:IGU=,iv:zc7DLvdKGoMQthnuXbfchgLcckBmHNQXd4XkRM8n+oQ=,tag:tYEuaQe6rzDAF2F1fmlUtA==,type:str]
kind: ENC[AES256_GCM,data:zJpK88Qn,iv:J3ngOFxD1Dc5lBMNiLXftdvRrHsDNIeOPeXN+/O5Ra8=,tag:qabOoYTyV/o3iMATgCgpVQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:5lcC33veTsZO,iv:nZysEIq/VZ0sjpDcmGaQly9qyo7oBO0TRKboUpKdNa0=,tag:VUCNNy/jl5pqN1CrSxC5uQ==,type:str]
    namespace: ENC[AES256_GCM,data:+/5wEQ4=,iv:6YlW0++YXCBYo1wKaq6HMd9YsZi27sexmW5hRojlDSM=,tag:TQ3urniqRC6MAGrmGf7cvw==,type:str]
stringData:
    MONGO_USER: ENC[AES256_GCM,data:fEOw1WbP,iv:dAuw1zoy5E2DmRn29ya9GqngR+l6hoWhnA7gaeCzVy8=,tag:HooL0UC0GYm1hcJiTFvtYw==,type:str]
    MONGO_PASS: ENC[AES256_GCM,data:v4y9GBwMXJf5EsDTUCdX32XI3JGNN38JsqpOHvrylaUsNFd4OSE+5Y0HEIgSYzwJILAjAM0J9UJaGUw9T3kDug==,iv:ZHfwn2f2aN7jSd85IycUUFy856rBjK6GFyYzaU1/RyE=,tag:p1gS2o2khDCBrSTs2ny77A==,type:str]
    MONGO_HOST: ENC[AES256_GCM,data:QzJAcLYXIEF6mcw=,iv:zvjxHbth1RAWhzbVeT1wTcVO+vYJvSSCJiACzohPcso=,tag:Og/XOGXF1LmR7B84/gPXxg==,type:str]
    MONGO_PORT: ENC[AES256_GCM,data:Rfz/S1g=,iv:cV81gIR95lK1NheKuRmvcC0LPRsEGcuJUBS944X00q4=,tag:v2sw2l4XzjDEKFB7gQ+iFg==,type:str]
    MONGO_DBNAME: ENC[AES256_GCM,data:9iBbp+g=,iv:jyhfXii8Y1f789blnr/KczCLdFrmaOtQVPTJ1t7AivA=,tag:2dkjAGygzBa+fOpSW2AeRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWTdTQ21VbXdsRW5GbWNt
            QjNFbzJ5RDZRMW1iYkY0aVJkcXpZUC9USUNFCjdWT2p1ZEV3VzBxUkFObTl0SVVD
            eEtEMUVNdDlzMGNoSG0zNVFocXpFQ2sKLS0tIEo1RzZ0YlZNNTlXSG9SVUFVVGo0
            ZE1lQzZLN2NaUnVJVmhIbFpWTVFpdFkKslhhkzWIBMVJMHlQbXTPZKG8QQ9DPFyX
            gE/OOUViIFwRGec+7+kfcY89N4KpuQLIzLYqyAAMIrHppGclnaLgQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl0nmje9vetdgudflgcnnydcg44kv9a5px4e8lhyaz3qfqewjfhqhdg5ra
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNG1jbDZGZzl6blNGQVRW
            N28xanFuZWpIV3U0ZjlMd01nSjczQ215UVNZCkJ3ZmFJMkFyTCtIUmJKSVBpb2FG
            eVhGdVBFTWp1dElLcm1qYnd6RnFBZWcKLS0tIFE5QTMzWTA1Z2pPS01WV3N3ajBt
            aFFhSlFNMGJPd1p1Z2RpcFpjOUFtcUkKvMIIOgVNNpBvgdtagZsrTxA+TNmJ4VxH
            8wTX1bYJdvmuREojVIAHC5lfvEgfGdpRodARARRTJWKZJ69gjipwAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pxc3l7nck3ku25nd66f5ul0c0gkhtnjmnr3zk0ftmm2yt3qn0q8strdzdy
    lastmodified: "2026-07-06T11:29:33Z"
    mac: ENC[AES256_GCM,data:VCmwZpc5vyKyQByD43WqkIm1VPExpILcL0I7M2DkAPG2gkvz+QeskAGTevPMfjB2CiSkr1kycz96yvn5t0vFB9td7HX+n+pc4O1aA44L5aE8YmqdVp+CAUGy9eM0oxX1Vw7DeKj7ENxpe85EnNIbLyHSs9ELpcOFcPehbGJOH08=,iv:OOvLklOI/lX8bqIdj8t99/GmDydBc8BswQh2MReh56o=,tag:wjYKqpkqTgHAjaKzmbbfNQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
