http:
  routers:
    bazarr:
      entryPoints:
        - "websecure"
      rule: "Host(`bazarr.local.bookorjeman.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: bazarr

  services:
    bazarr:
      loadBalancer:
        servers:
          - url: "http://10.10.40.11:6767"
        passHostHeader: true
