http:
  routers:
    esphome:
      entryPoints:
        - "websecure"
      rule: "Host(`esphome.local.bookorjeman.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: esphome

  services:
    esphome:
      loadBalancer:
        servers:
          - url: "http://10.10.40.20:6052"
        passHostHeader: true
