http:
  routers:
    lidarr:
      entryPoints:
        - "websecure"
      rule: "Host(`lidarr.local.bookorjeman.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: lidarr

  services:
    lidarr:
      loadBalancer:
        servers:
          - url: "http://10.10.40.11:8686"
        passHostHeader: true
