http:
  routers:
    mealie:
      entryPoints:
        - "websecure"
      rule: "Host(`mealie.local.bookorjeman.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: mealie

  services:
    mealie:
      loadBalancer:
        servers:
          - url: "http://10.10.40.20:9925"
        passHostHeader: true
