http:
  routers:
    n4:
      entryPoints:
        - "websecure"
      rule: "Host(`n4.local.bookorjeman.com`)"
      middlewares:
        - default-headers
      tls:
        certResolver: cloudflare
      service: n4

  services:
    n4:
      loadBalancer:
        servers:
          - url: "https://10.10.30.10:8006"
        passHostHeader: true
        serversTransport: proxmox-transport

  serversTransports:
    proxmox-transport:
      insecureSkipVerify: true
