http:
  routers:
    navidrome:
      entryPoints:
        - "websecure"
      rule: "Host(`navidrome.local.bookorjeman.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: navidrome

  services:
    navidrome:
      loadBalancer:
        servers:
          - url: "http://10.10.40.11:4533"
        passHostHeader: true
