http:
  routers:
    octoprint:
      entryPoints:
        - "websecure"
      rule: "Host(`octoprint.local.bookorjeman.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: octoprint

  services:
    octoprint:
      loadBalancer:
        servers:
          - url: "http://10.10.40.20:5000"
        passHostHeader: true
