http:
  routers:
    portainer:
      entryPoints:
        - "websecure"
      rule: "Host(`portainer.local.bookorjeman.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: portainer

  services:
    portainer:
      loadBalancer:
        servers:
          - url: "https://10.10.40.20:9443"
        passHostHeader: true
        serversTransport: portainer-transport

  serversTransports:
    portainer-transport:
      insecureSkipVerify: true
