http:
  routers:
    router:
      entryPoints:
        - "websecure"
      rule: "Host(`router.local.bookorjeman.com`)"
      tls:
        certResolver: cloudflare
      service: router

  services:
    router:
      loadBalancer:
        servers:
          - url: "https://192.168.1.1"
        passHostHeader: true
        serversTransport: router-insecure

  serversTransports:
    router-insecure:
      insecureSkipVerify: true
