http:
  routers:
    sonarr:
      entryPoints:
        - "websecure"
      rule: "Host(`sonarr.local.bookorjeman.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: sonarr

  services:
    sonarr:
      loadBalancer:
        servers:
          - url: "http://10.10.40.11:8989"
        passHostHeader: true
