{
  pkgs,
  lib,
  ...
}: {
  programs.ghostty = {
    enable = true;
    # nixpkgs has no darwin build for ghostty — install via homebrew cask there,
    # but still let home-manager manage the config (package = null skips install).
    package = lib.mkIf pkgs.stdenv.hostPlatform.isDarwin null;
    settings = {
      # Font configuration
      font-family = "JetBrainsMono Nerd Font";
      font-size = 12;
      font-style = "regular";
      font-style-bold = "bold";
      font-style-italic = "italic";
      font-style-bold-italic = "bold-italic";

      # Theme - on Linux it's generated by Noctalia from wallpaper colors;
      # macOS has no Noctalia, so fall back to a built-in theme.
      theme = if pkgs.stdenv.hostPlatform.isDarwin then "TokyoNight" else "noctalia";

      # Apple glass effect
      background-opacity = 0.85;
      background-blur-radius = 50;

      # Terminal settings
      term = "xterm-256color";
      shell-integration = "zsh";
      shell-integration-features = "cursor,sudo,title";

      # Window settings
      window-decoration = false;
      window-title-font-family = "MesloLGS Nerd Font";
      window-new-tab-position = "current";
      window-inherit-working-directory = true;
      window-inherit-font-size = true;

      # Dimensions and padding
      window-width = 170;
      window-height = 45;
      window-padding-x = 8;
      window-padding-y = 4;

      # Cursor settings
      cursor-style = "block";
      cursor-style-blink = false;

      # Copy/paste settings
      copy-on-select = "clipboard";
      click-repeat-interval = 250;

      # Scrollback
      scrollback-limit = 10000;

      # Mouse settings
      mouse-hide-while-typing = true;

      # Keybindings
      keybind = [
        "ctrl+shift+equal=increase_font_size:1"
        "ctrl+minus=decrease_font_size:1"
        "ctrl+zero=reset_font_size"
        "ctrl+shift+c=copy_to_clipboard"
        "ctrl+shift+v=paste_from_clipboard"
        "ctrl+shift+n=new_window"
        "ctrl+shift+t=new_tab"
        "ctrl+shift+w=close_surface"
        "ctrl+page_up=previous_tab"
        "ctrl+page_down=next_tab"
      ];
    };
  };
}
