---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings
title: Axensvägen 13

background: 
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 50

theme: dark
color: slate

layout:
  Proxmox:
    style: column
  Infrastructure:
    style: column
  Docker Management:
    style: column
  Network & Monitoring:
    style: column
  Home Automation:
    style: column
  Media Server:
    style: column
  Media Automation:
    style: column
  Downloads:
    style: column
  Personal Apps:
    style: column
  Storage:
    style: column

providers:
  openweathermap: {{HOMEPAGE_VAR_OPENWEATHERMAP_KEY}}
  weatherapi: {{HOMEPAGE_VAR_WEATHERAPI_KEY}}
