---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    env_file: .env
    networks:
      proxy:
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
    restart: always
    environment:
      PUID: $PUID
      PGID: $PGID

networks:
  proxy:
    external: true
