apiVersion: ENC[AES256_GCM,data:0J0=,iv:5G46Qees3oMEZc6+faC9PRdRx4d5WGDUJH+RIPnaaN4=,tag:j7kLDrGAkvCuaPrtwoyt8g==,type:str]
kind: ENC[AES256_GCM,data:FhB0knCC,iv:AzU4qW1QDyYrrUQqV5BnUZi2xwdK5eb4QXaahzv6qOM=,tag:CK9xU+m01U7nFtU37dm31g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:i1C/5QkPHow88544Fg==,iv:PDaHVV7lql0DZ/OLluzsjdbZXIoEuG9FNVpL+KkVsMg=,tag:Wv/VfiscHtrW7tpl3fIFzw==,type:str]
    namespace: ENC[AES256_GCM,data:h+lTBAlBSpPuzdGFew==,iv:62Dv2gAPhMWimQi9/+yMsWb4M+6FuIFJEnPqrunAuOA=,tag:tCKnNylTEuzwM3Eeo6/fig==,type:str]
stringData:
    TOKEN: ENC[AES256_GCM,data:a+sGytQsSUQYiD3muVU65tobhP1K1pHXu53lTW3XQMd/6XwaEIZlApVuel3PNzKRXYlYLvXIgi4hAaeS/U6MdqMz37+9e9T20p76PX9TOqzv/arlxQhUHuTGcwf9gQ1ovdq0tU1Q6NaeoKuk7L39oYu888PWg3ijoftRXGw4/23D6sBChwWiqNuqSvA8x+IXjS2B18S7v7g/rNDZG3O6y+vvddSCEDBcOwgpw2FT5+6npM0BDicd,iv:XMvLO92+nFM8Bg1T+yBtWdw7e7keSGPZZAynotYkUus=,tag:hf0SbwQGWFQ07nWyIpUWpQ==,type:str]
    INFLUXDB_TOKEN: ENC[AES256_GCM,data:B4FH+KN2UYFgAwis0aBYlaZYHiLuys9t9a6tgC0w+BJENDy3K1QFq70bOyS0fUFzUt7BPN5EoxKY08c1sklrdO0vmIlNo2HYU5Tac3/YoOeYaJke9W9a/Q==,iv:McDkIIMANfJZpZsqSLsBVL+j/+/4hT2wnqAuwfuFnqk=,tag:zNuS358FvtaHJhQv2gHfXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnelVZS3AwTTBMVHpmWkRY
            RzkwMHdJeG9YVUFvOTBFYitoTlV6Q2t4VUcwCjU4NWtXUlRxbGFST3lHa3V0eW1I
            c2hNaDc3eUNMeDZXT1lRSjFkNHNwYzAKLS0tIE9uanRQWDJSWnBlUlNnamVIQytP
            QWVjd2lWbkRIcEJCUm9FczFna0JRTTQKHb2MZG3W4oGsrVA1Nct0E3nutmAzeFY+
            otAKzDO7sgJ+m1ywRyIyDhgO/1J5oVXYwaUyMTuuwvGyEltxF90+VA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl0nmje9vetdgudflgcnnydcg44kv9a5px4e8lhyaz3qfqewjfhqhdg5ra
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSDBrZ3JxV3VpOWhNV0oz
            L1lCblZYY2Q5QUtUT1g1aFdYMmE5eEFDbTEwCjVvZ2RwcGRTSS9JbE9BSXJPcDdp
            MWpjc3lJZFhEaTJMU2FWOVpLZzhia0EKLS0tIG04MUp1cE1ES1NZTFg4NlJ1RUZU
            Vk9JOHI4ck9tQVpPTFgwTjZpTEF6Z3MKsprlkViQPU7JB3XISe+dhtfhU2DRLXaF
            EjIOpxL4CgDQi7o9Ug29165P14uqaUtEn3nep48EEf86OknFdHF3VQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pxc3l7nck3ku25nd66f5ul0c0gkhtnjmnr3zk0ftmm2yt3qn0q8strdzdy
    lastmodified: "2026-07-09T08:38:59Z"
    mac: ENC[AES256_GCM,data:hPAFiOdZeNGGtSUNQwsvSyyImqK6KNRvSashfTGL82TtSjEjjLqbzEsdh3/+89NjuLt/fpq4Gcg69HEohDW731W4OIhRrhBupB7OpBlwWRazsLms8Yk6qMEhwzADS0cv3MKN9JrcV5ASfWQYhxus+AxozlpYlRgOabNlfQlCmmI=,iv:vegmj/WPd0qIBHTL/raBoKYswNR8GveSmZbKFbQsLe8=,tag:udeFjkEBWq+7VUNmpTb6cQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
