apiVersion: ENC[AES256_GCM,data:Jv0=,iv:tIvr1YMO4RCZxcaone9HaGMlLfVRJ1uOPAIT21Xx2b8=,tag:AT5XCQ2me+zTs+gUQ+0x3Q==,type:str]
kind: ENC[AES256_GCM,data:0FFvLcql,iv:YlBolvTeKCKSUeMraAAsqb13JgmTcob63d7jMH3/UWc=,tag:QFMms5LAME/yhhMA19LXrw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:z6UPEmUkHYXdZ6cc3w==,iv:FrkGFvYpt+okao/ISg+vftYqMwr9oRONrG8zdiGmCnM=,tag:6TWBiMG+e88MAcgBlsyMug==,type:str]
    namespace: ENC[AES256_GCM,data:P117YWwp/I24XG7bzw==,iv:HN1x3mwSs0iXJ4Gw0WIq2NgO6FsahmDiqsweeA97YNg=,tag:TBvzddH9DlciGx5Tfjx/CA==,type:str]
stringData:
    TOKEN: ENC[AES256_GCM,data:RIuaf7zIsHtB/iky8NnVYNwwMG3iByZTyPrVPjceRp3yhG0+A5g34WCcLSoTtEhQ00oR3GwqJJPD8b2uvZkiLau0JRFFp68qzACP1puUlhmagAoVqOua6vIUJBEV9Mx+wc5ZvzD8+LXpIWlUMkEnLFJldcW5QzWw0TJlRhewIf0horOURLGkQV9DnOVRbzPO/6tFh4gTFDUpMq3fmtKqk9ngMQBgv4a5yFqfYlHrAkY2aO7NprWs,iv:TiniE2yr9MW+UhvE9ZMa1hEZH7dcHiYNg2Oysb1WMyA=,tag:SI6p8vKgh1PooNK61r/uHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbnhJeGlEUWxUVlo2TVF6
            a2RDdEtoNFlzSStYRHV4SUh6dDZENDJhc1VjCjA4SU10T0RPYlhPbE15bDZNT3hR
            MFFBRURxQUMrbHA3M3BmNTg0cHZRRm8KLS0tIEJ1N1RMYkN1NGN0QWlPcitvTnNB
            NlJON1ROQjZXd2xNd29uZ0M4UXZSb1kKFPBqhJrLxf9Bs0rS8QGThn8YHZ1dCNU1
            GgP6lcqUKRIh5Hs3OlU8MW5XxNnOmu2N4F9oUBTDdgBwMQBZOMcxDw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl0nmje9vetdgudflgcnnydcg44kv9a5px4e8lhyaz3qfqewjfhqhdg5ra
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Tmh4U3ZZMXNlVUNlUDRT
            dDcxQWsvU1oxWU1GQUFqSi9kMWNHZmNUQ0JRCjQ5eS9aVUpUL201dzhBMmlBc3Fa
            UHc5MUJSVUdydFRyODV1bDhKTzN4UFEKLS0tIDNtVTl0c3hDR243VnF4YW1tb2ZF
            dHViTGF5YlRtK2g5ckRGaVNxNjdySW8KpcYXvw5S1birSwngHfqOsVqsnww+xW4J
            pe+msPZpAgp31GV4yM50yEmrzzWjTOyLtijbQyO7uOjwthlphyAHHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pxc3l7nck3ku25nd66f5ul0c0gkhtnjmnr3zk0ftmm2yt3qn0q8strdzdy
    lastmodified: "2026-07-09T08:11:36Z"
    mac: ENC[AES256_GCM,data:NunhlbcprjRoSTiGpyN7SKvn+LpUuf9rPX56IWpoSUxqZHyQLD8MCNOtqXy7AdDy4CcDSNeIx5xRizn9ollRA1DDPq3Fr1CCzSVA1MyolA7Ry9Sz6Ud0HHkq/IzYYkYG6B50uTgV55z6gp0Wncpg/m/+SlJ2qiCcPONVu1HjAFM=,iv:6EInI3kyHuhJu8QsGTtC3Qy9Y9uwdNJMmJyz5+Ckbh4=,tag:/qX+5OsdyrvFsnlEHuX67g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
