apiVersion: ENC[AES256_GCM,data:ZWM=,iv:L8RnkyZPBZNa9dKasomw2cK/VkiqILQnygUkklG99c4=,tag:MdVWJ6nv2lzoKb7gyac+0A==,type:str]
kind: ENC[AES256_GCM,data:HhTtYkPJ,iv:K2atXD3+uv5MAW/fEwYPbDooZzfj9l/3kui2JVqPSN4=,tag:AAhTwtxZscOaBn59NCN+jw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NDwVSZeWUU6Bfq9XzdH/,iv:t9NfJ36eGguM0F79Aw2dUWuWKoKMawvc1fOU8+s80lQ=,tag:9k0rtGrxh0TYH1vbFacBhA==,type:str]
    namespace: ENC[AES256_GCM,data:4prkfhQEqqewSa0D+A==,iv:c+ejymdQ1yWSjmwZEIYNhswSjxY3Lk6SlGRr6KB47nw=,tag:pF9SpF+6LtAmxpZgg0cvXA==,type:str]
stringData:
    passwd: ENC[AES256_GCM,data:0kwm8cj6r+C6pYBgWf5biPbg0b7of8E4RxV5NVf7XZuPc1iI9smhWhfC68CPdcR20xUlCSbsnHj3ChCpnNb2KEuIsgx0rm1lwjCNeIXvkX2xXNT5VW5PE/vox+3X2Yr7Yzg2HrasE0FRYnB7PVxn4cCe5I7zph4X+/+uWdcKXRO2FCYEfPf+zuMuMyx1lYRfpH/ofxXGfLXmDXjYdZoEoXFw/iBd1dPk3QVxFAnHiPJwj0C2QUX49Ji/+kJgcqw+W2Cgf1Hwta0BLAOq4hp5cqeKTxNvUlxswsPZSiHdfnVyvj/S5WcIvE+lVKcuGAedu8LlHu3eKx4BvdcNEstAePVPiRwBn3xC7nfPUa8/9xTKYTxzQRK4WZi9TJjr1nVggFH4JSt8FjBq7vcmpHyILFTgnFr+UUv5YIoUdnJzO+En2ORZGVDrfvw2tBuHACIePdDvXBZsCQNaPC2FLQQzB3m8rfq5FwVudRpIM0oAyxtl9wJAEAaQii6YsrgySZYaWlSDRccRv5tr1y9ovJk=,iv:kLoMH5gn06tqgpGf7fRgKaKU1/AfZIOfHOcPkDj+VGA=,tag:eTG5K0si40cbpnRWJcAIJA==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:QutUhe+mrRoL9gI=,iv:W2o2fnZTx8xA9Ykh9RfpDfyUVdjV4Yn9QwQqUiA05hg=,tag:8TmwDz8bmE/Qo6KcIGAfjA==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:9acuaT+NCH5aW9Yvzp/EAN3bzyFXZ48esNghlG7KCH4=,iv:+Lg9pPD5hu5lsAbFSMn+aUmL2/hgwRCsf4M8o+L687Q=,tag:iKBpyMOBaCKOkl/pOERocg==,type:str]
    HA_MQTT_PASSWORD: ENC[AES256_GCM,data:LkHBDLQb/CrUFlH5z6/dW72CqgfwCugAAxo0Z///EDI=,iv:pPlB+vixcG4dmMNyXpngGFv0ZQNtXr69YmtQYx5VVyA=,tag:zyAq9CE78+l2bD88VdOIbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZzhVVlJkWjlpQVhscWFS
            c3BFRnRMMElSejJXcUM2cXJLMDBlaTNmODBNCk5TNDU3MlMwL252WHVxTG5laHcw
            dGZaNjlOamxtb0NMRXkwaGtCVFNRR2sKLS0tIGpYeUs1QTJTay9XVzhwWnIrMmV6
            YVNrYm5qWWxRdlQ1OFhBRTg0MTB2N0UK34knMoZWI8pyNUM8x3HBHAwvq4enNpwO
            mH1WYuqMBZnEvYJSicG3RGSAQKah0FZpagI0VzQPOXuXwclCUIPOQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl0nmje9vetdgudflgcnnydcg44kv9a5px4e8lhyaz3qfqewjfhqhdg5ra
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUDY5V01EUVR5TENqOFpF
            SHI2YmJuZDJOUTExMURZdlNMdUZ5SnMwR1dVClk4SGU3N3pBN1crc01yYmxodGN0
            UTB2VnVqblpTbWM3QW9YWSs1S0RJYUEKLS0tIDk2Y2FNYzRSSVJlYkMvQlRpaW5i
            eTlWWUtyQmxjenF6S2xsSVVDdHNwbFEKYeAAclRvpKiZaPAS9ocgh3U31xbgliVB
            fwVF1aHfC8iADgJDq40GWXTDyepcfDLgCvunkzbqhmm/mSRp9m8ydQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pxc3l7nck3ku25nd66f5ul0c0gkhtnjmnr3zk0ftmm2yt3qn0q8strdzdy
    lastmodified: "2026-07-18T21:57:33Z"
    mac: ENC[AES256_GCM,data:k8/XXv3VRvZIpYuM6a0op26WY2m/2yh3jPe8fqniBhFUt6A7HQRWP+EM67fT+L8GHH44yGV5gjuaJLvAxQfCP1xChn9uysSQRhW2JOWxYdcUrwIRZ35eSeV6vCPJhBRtXCIH24i0Au8GESuzHP3Ivspoib/qa8gqzdQmiEfXD1U=,iv:6VrFrpfDEpDCz+DabtFbGUOFzGw86s+X+dHZ3HUbjcs=,tag:7tHbid2+UKntLebhTbtAMw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
