apiVersion: ENC[AES256_GCM,data:X28=,iv:iKcvjgos+16jPm7wxUED1WtfpYC7kB31Rn/fBxgFmvg=,tag:LgOg/QI/KwLmUbzn8Q/dmw==,type:str]
kind: ENC[AES256_GCM,data:oQ3umoTV,iv:V42c5h2XG7WxVkeve5Cr3x1O8AnzN8/kVYOZprdUQD4=,tag:IYT7De1K8PEqnGJVs+50HA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Xrub6MNzl0a/X5E=,iv:ZV9yxr/v4c/g2Te7p4oN9zqy+3fthhlm3M3l/iRdt3k=,tag:D+tt7e5FHavChaG1j3dv6A==,type:str]
    namespace: ENC[AES256_GCM,data:s/tcoxu8yw==,iv:DU0eW5wNE3LN40ypS+WlunHqsfUqmHFUEvFEL5GZeP0=,tag:FFXR/5bLByFzzScP4b//Dg==,type:str]
type: ENC[AES256_GCM,data:t+xZn8nF,iv:qoiNOQkOZY7F2i9H5PX+EZyLxr5oDPu3+Xmwopu/BOY=,tag:JU+/Xz9lMUZNBtv3CRuzWg==,type:str]
stringData:
    proof: ENC[AES256_GCM,data:+iDN/E2EO6F2ZLJcJNFcA2aSRw==,iv:AVpEq035H6tq2Teti3jqluwDuNHbRVfH3ihko4lZLHU=,tag:YirKrMXe35f7is50xSJ9QA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdTFIaGdKVUtQamVpR3NO
            WG93YUU1U3kvdnJxVWxRcUtJbGp4RXRDRVZZCktKR1c2UXQ3YzVlSUxFNUtQSmFh
            OFJXQkRIM3JKZlJhNnZiMVdEYWJDRW8KLS0tIDFDNzRUOFRVS2tROEI1bEZQTi9R
            TWRrWFNCcFJ3WUQyUlpKNVJiTDBqc2sKF0gWOAK2j3hNJzZMZpacoG0FlTvRmuOZ
            Yaj0dTDDjxLy46vTqIduZKFmb6x/NU06Vg1D1K0/Ry9w6X288C/47g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl0nmje9vetdgudflgcnnydcg44kv9a5px4e8lhyaz3qfqewjfhqhdg5ra
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArT2dWdVc0S28wd3Bvcy95
            ZEtFNmU2YXRYekhKd2RHZGhGTEM5YzI2akYwCktuSUU5NG5YQ2hSTFBacngrK2sy
            MndHOWZVUUp5b25jdmxKSjQ3bmJQTFUKLS0tIDlTV3QvM2dYNDM5TnhsNjErMTY3
            azZ6Y2g2VmhySEtIWW5oSU9GMHpoQkUK8N89cpsJ7Ja2ECf4kad9ksniSjGznCwY
            sRQ5i6lIVfjbWjW21t8U6vTevFP0OasALSK+ImUjO90JUm7/xfVrzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pxc3l7nck3ku25nd66f5ul0c0gkhtnjmnr3zk0ftmm2yt3qn0q8strdzdy
    lastmodified: "2026-07-01T10:05:38Z"
    mac: ENC[AES256_GCM,data:BSF0FnLKQ7cIRIeHIpx7yiSuvcIDjVZDY/TYhAEkk4ThuXHApPwyXurJKaBga6qyTbn3R4u5/dX4N6sEdEfUEAgsA8glOd6hYjYDmkBG+Spn/4bc+ZBT8Vo1Fa6mwD0gHecKCYoHcI8I0tJpOtxP/1p/a9ocP2yMGgWQ3AOpQ70=,iv:w+rfUG2sOcuioG/oImPwF42aEAx4IU6axozcfx2gIwk=,tag:Pr+lGzUFKph44pS4yxp6+Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
