#ENC[AES256_GCM,data:8p/l3uhO5WHrlAjoMQVGsrK/0b3KHcjkQZmW/5mtxNx+D+ATdrG23r6ZlfnLzPc3+2giDSwrsCOk68FFITtqJGbxBD22YQ==,iv:MKvu1/Hgbl2qLJY1Qd1LraPHg4rL2AyLkk8Bu4PprI0=,tag:zTuYvRVk1P6X9JRllFLhAA==,type:comment]
#ENC[AES256_GCM,data:/+OpqEczXtWE0bdEb0UhXqpUFHuI5JYJfSUxYxJmxvjtkO0UnAY+LJAlxtUXlq0PMrrZJ+cCOhKhJGYRIpJuCMTKceOdJ0k=,iv:YGK340kpamJYGq2KUzhSbr/nXQuqV8b/jo2yR6agPAY=,tag:i7jhdB8T9X+em1W1/snO5w==,type:comment]
#ENC[AES256_GCM,data:3rgFWFqK5Gp0Z09bar20ikTxIBT/bQ+i0cQjQ93HkqqUtK84+fsCjEqE0g8dhRhbAkWA7Xjx08qwha03UpgWxbjhKvWcmjsHJ+/xYQs=,iv:NPIZM2lhpw7omChqIR6u2jCpLOq2gWSdkoaOUTlwbww=,tag:8eiS1WHOasRAjYpCOu0Nbw==,type:comment]
#ENC[AES256_GCM,data:RSegBMARdxq11DL5fuEln/X6V5y2SNULEvAKr8XWW5zANugFGIW9763UtVadzwWs5roWD7Ltrt4BF/vNJWrGNG7sb3f4dXoQpA==,iv:TCofBzghkVYSWwX7cY1rMIXkDv7IRYJUBSsF12ryNaE=,tag:CwZeB0eTubwEQR/kKhRFiw==,type:comment]
#ENC[AES256_GCM,data:ikVOTwZtqd6nHIaNMnO8xYgKwWPKaikICoEokFcCxI6JfOX6oxDUncyFqCTyScc/IJWrBvSxUM+FH+TByy3APtJJ6tE6,iv:PzcLUzj/pz4c+SocniwvScrPAs2/lP3SFcyJXVbeswU=,tag:dp/1HMmVu+kvOlsTucVmeg==,type:comment]
#ENC[AES256_GCM,data:TvxVgParl7AfUqLcCw4d,iv:vDtjRhS7vnxmbCGWdE7hGPHfoliGb2UrJ8ooWEpBFyk=,tag:8RG8KHFaZjuve2+kCdgHAA==,type:comment]
apiVersion: ENC[AES256_GCM,data:V4I=,iv:QCefN4A+/YuJyfHUTx9LyC8ODPP8Tb68S0/YjtUQbcc=,tag:+M6X62XpsWEeztPMtP+Fyw==,type:str]
kind: ENC[AES256_GCM,data:O0A6+FzM,iv:HIHVgZDIyIFqHt2oAAqP/5cY+aIjZpoaoHnON+Oln20=,tag:OqRNMJ8CAPayntF+qQ22KQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rgUB4v5mu6VuiSRe1SUwUDxX,iv:vr8N/YaA0sjW3EIjX4qNkXu82tmXCVULbwfdMTQ6bms=,tag:HbsnsEqY+B8S/8plKptHoA==,type:str]
    namespace: ENC[AES256_GCM,data:P40Ahr7ofrBNvSsopus=,iv:YUOfNB8oUw/4BysZSx83BkScq9/+5Ox/rtKo/Ee0kCU=,tag:Fg+z0zDv52wEQYHjnVLsJQ==,type:str]
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:ZoB5K6gVNDkaCP4ga1lrj5cz0Qk+MqLqPjuqOPKd/pQ72Cwy3YaqoN+mUbai248728YcImFTLRS4XUhhvMSQNevqy+wOOehZfeJvgm8rken2BJfvkBrGom9eXDp+UhLq9d2Gtk7ByNNjpmID67FaY1rJCUgmNXceOFJJ3FjFeraBeKGyTmpRQBVOKeTMDgDIZOO+u4GZVP8gm3FPQxD2BKTTLASNr7eq7QzhRFRfE4Cs6Ns/BBywI3OYByjxq9me7iyGVue9tdxTfyCcaDb4RDLdD/UFUimxnDTvONblcsEhBmuTpE3IX9Pvr7mqbKEoJcn6dNG4FTpMlU0EaXdfa6G08ZPZxJOtwlWRzbpSelMiVgWQ60E6ggRk9f+u3FV07d6H2YjdqpD7n+hgYlgOZQV2Fc1stDfBw5V/E55peGpFY2AH6u3qLGut+kX0TLpitwSMvivNLyJvEJ0SMI6DN5qVZ6S2xqeUv9/7+YIekGU+RWx3fYITCdQdHklBeA1lbAZdaYDBzEGijYQBYWNYNR+XUb2dUAPmVkxyFdXgV+kbqrYBebZ7ZIUeTKZgWfn6xBL5S9YBhgRJTswD5xP8cHpAnMd3ZlSfbzXnHPfCVu9/2jCCvP7QGfdyBSO52dwRX0SI7oOpAH3jfMpAyAAvJ1YZOf0jTUE/qgCx3DlTHOmjxgB83avgZ0tPcdu0+irInPFI4ojgg1NEGmyZzCQMvVRioYgzcdXDBEuhgjha5ZtXlbyyK2WNUVTCvyZ00X85NsrtK3GoKg==,iv:PK4hmmNudSQ3UYQbHkQmRidcVy5X1K25K+0bknSCgAM=,tag:kpAYClnsM4n/CemRhV6ekw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUEVRSlRQd1RtQ0VBbUpL
            amw2S3ovczRPa2dMQ1FzN1RHejlmaTg3eUJnCjgvTFhVQ0VDRjc5RmppaG1pbFhU
            L3BySGJLRGF2cGhRdVEvdmtRWDdlUDAKLS0tIEY3dTc1T240WlpnSnlaNGUrTHEw
            Z3dUMFFoWkFoMW02aE85WHdud1ZWNlUKtcihghEKhPKsDCpNLJ3QgDjYqtne8S8x
            jgzFCWtiECeFIyIBaR/R0mQqnIGXv5u9NE8wiYfvgTI2qbq1dmflbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl0nmje9vetdgudflgcnnydcg44kv9a5px4e8lhyaz3qfqewjfhqhdg5ra
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTGJnQW5tSmwxY3hoUm5H
            MGZPVHdZQ0N2bDB5d0FNY0JuTjg0bm9tOTJzCmt3cDBlekdnTUtQVldnMTRiVUFk
            M1ZOZ3A4TGZ6OXdDN1VRRnhNN29QeHcKLS0tIEgvdXpvY01EejZKUER6a2tHbnFS
            N3dKcGhscHpwa3NUWE1KZ2xOOE0wV3MKcsMkabcx/Y08ppVlRudas6vSMciKhHrF
            Yal3FAfpiEs3C/KyFwf8PIKPenrxHdM+UYoY4z6QacALSQ8Fg+BJNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pxc3l7nck3ku25nd66f5ul0c0gkhtnjmnr3zk0ftmm2yt3qn0q8strdzdy
    lastmodified: "2026-07-03T16:29:17Z"
    mac: ENC[AES256_GCM,data:p346ozWZVHGxcSfbPa3dDlxnUCc8OUfSaPYWx+QRINpbcg2crlhhMcCidlxzjFqHAKgHS9aQM3MMEUJTRYYnnWgfa93FQM6pGPU2BAeQ3C8l+esQh7ga8K1wnfJQs5JSIbz9d3eRd4rPJRu1J8QseLdiJUuYH96lf6QqllQlYds=,iv:FldAa2t4sZTQU8Yu6/M2uEVPrl5yJN0DqyrYuQSqBug=,tag:vP6h40o3AMC7xrbk9342/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
