#ENC[AES256_GCM,data:fI9rv0b1UJTZGsrpdUi1k2ptXEDubq1ACRUc3mE0hmYJb7bbJII7JMg9weaInJf7OaKAiyn87Iz02tdBI8rujcIvbSlvkW6R,iv:TKo87VH88lxnKDZnYQODizG6ZMnIWO/lpquM1SDSnoc=,tag:fiAjmMHHax0MDWhn855a6A==,type:comment]
#ENC[AES256_GCM,data:AlIYs7tg2UR0Z0Zxoxc1aPdxQ1AJVDTRLYW/q/toaGuhwc94KrzeVWgYoQcgx2mkrNUUMvszduoX0qfb1DEJkNkD0D3BCiBIMz7QUUM=,iv:0aKRB2oJzHq6CDQeWjsT44z/GueYCor/Vw8YmZNzrbk=,tag:ij3HWIXWL3P+1T1pyXM+Mg==,type:comment]
#ENC[AES256_GCM,data:XkV7uw/Mw7G18JQyIiwN1338oN/Z4jXTS3qu18rdVQF7GllrX2aFvEm6PylSIiw99nFhQ0m/FLqEa5ipf/ltIj0O75/oJWZJP59qCA==,iv:QToCTbtZ6vl9XIAy1K3P+wv4Qil1idc9k8nZfJFlf4M=,tag:dbo5SSRUL71XR0c0RSnJPw==,type:comment]
#ENC[AES256_GCM,data:eZtidqHk5SsyjpsL4m3qm7VhlxjVRtyswvYa9dcPUlcZiJY8OBd4NYtvjywnee2TdJKVIqtiRheUy68MkXbjhQFB3a95J6LLnMSMt2txsQ==,iv:MACN/NV7DX34O7n4AHdWcKVTMRys7ngalMHbd/4JbU8=,tag:ifOGXq+dWBS1SsZ3T/Um6A==,type:comment]
#ENC[AES256_GCM,data:mw0sraRMeq3ypd4RxV6T0lpVcTI1XHtjbGqPryHjqx2K8A/WJzh2bzjqN/Q=,iv:a8u7bQiWl02FaPCAnOgIA/U/TGzI8MW7yuS3Aa0Oi2U=,tag:G5+3CUN+ZhpxCQgRqPmNRQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:5Sk=,iv:IPmgTn/WSX2y+wU58hmgUtRtQGXf0SHzru6QqZ/Q72M=,tag:bjU6fmttAbd9T0vFNGOv1g==,type:str]
kind: ENC[AES256_GCM,data:RSGZ3+Ku,iv:qPtU2weiogjX/VGk9aP4Cl1W7Q23v9ThzhBA+fU01X0=,tag:SsxiDOxRU9JxTKB0UMR1bA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3hkj+ybbHsOyUmKEA89dUs10w58=,iv:hVSSnZUy83cx0/fnA3TUiX7ILWTDJdB8vot3yTCh3nY=,tag:oGOCodOxCNPydaj/E/KN8A==,type:str]
    namespace: ENC[AES256_GCM,data:4jX6dz9DFjsBkBYphAY=,iv:eyegMuPMeppud14fiuUqgVfQr6bNZ8zIbVJjmxxaaY4=,tag:48B/Pmm5OnDB/I3ac0rzWQ==,type:str]
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:lnuVKGXUlQl4SrziI49Gk6yvLsvrAOdyMwx8jvLLAosPTeDfAWzCD3TL4k9WNXyB4C4g+wm0ps2NEuropZAhkE27bYgXiSQnUmbeZWKPnaDxufMv8vljKP+RT1KnqZLUt8Viq1071t645y1ADSGdCHmsOvOXGarDMPGQPrIoseoOjGiEhPYDM6NeI40hpJyKsa0ngECk/DoQutP71H/cVwDca4hCPYKDgIPnZbqMJ350HzP5nr2a/cfd8U9C7bfp2xFKK1Du1f1Px9By0RGN8CCmZ3SU7+GFBsVCDNJvv9DV9/5VpzX6Ig2MNAQF0w4pCbdKzTDGOgHI+c1oYvy27Yw2w1kcyW1mMtU3vLJPiUTtRa4U7yVWxTnBL1op2CdXKx/hqgTKxRZmprWikks7ALf0tBq2ISsgtchL6ryMQh1RA+4nJ/lQLOiHUaNNv7EIpWGJI6v7/dNrhWt48mepyjS2Yb8RAsxmycQ0bMbKN+Ht4GI3pDZlkz6GAgWMjrzRVH8BUGejOg80eVQ7n7Bj1L8bGyGo7LiqbTy6DFEB5AGL+ogp2P+v1L32RobRG6k7ZLo26nh2waWoDEC5CxL3rYCwFvNs9AwQNf7cxIWrmlkvFNZvq8wYgwa0K/yl9k+5G8hKHaPcSqCl0qr6y319kNjptLG3ojOFDw5k0aaOJbyXmhn7xGQaPDalHxlOLoVgLv30E+WlTqgnBinCWE7Ju+bUGz8D9iK5PrY86HeqAPXLs/mNPxJELSsCbj0G1T1ud5U1ApRrpouIfzID32+g0s4ebs7yq+fP99Q0212m+DC6MrFtqaMNLHA9t4K3taVEDlczx5dzQrlCms5l1aGG0bMQWladk2Su5GdHbYQhAwwtnvsGPWmwflfwmwiBLUoYUTTF00VNUiMP6ZMV24wQFu3235p1m3sX4lmH5ngfIOxZ3xuUe64AbQFdD8VbpKtQO7u2lpZPKwZzpMoxZfxj,iv:UUzJ2VzaK2VFQXMwj3qlTZbCGYGxJcl2Ot1+BojgVnM=,tag:eteOk0Qoui2Bb6IGr6ONfg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrK2lJWnppTXZPQXBvcmcr
            MFV5ZndnSGh2REhZT2RnYm1RbEUzdWcybFhJCnpIejZOVXlMYmZoQTBJNmpNUVFx
            b0tUWGhveUtHN1NEd0ZYTTFuU2k3UTQKLS0tIFhsUGo0ajdhTkZPYnZwV2p5MFVH
            RUp3c0JCd0hDM041elYrVTdSWHJxZXcKAyxCtfkpK3T9nLHl5Kah356gGFR1b8iw
            0J8kFtOfHBQOHD0hozWbDybj/wa9MAXcdX7mIzeqBygAU5hWqIfS3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl0nmje9vetdgudflgcnnydcg44kv9a5px4e8lhyaz3qfqewjfhqhdg5ra
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlLzhyUjFrcGJVZk5uKzNz
            V3pPbVBJMEFFakJPemd5blZrS0VycUt6eW5FCjNoQUp5SldCM3l5YzlXN2dRWFFE
            M00xK0cxT1NwT0dobkxaemRCNi9yZ1kKLS0tIDA2NDM1eHBLR1VYNkF6VSszMUZs
            WEl2NTlic1k1eUFteUpkenVhOUNNeEUK3fleoCedAGAX6duICm9dYMyxgrKuSrU1
            QTT8UuSt3OZn5KPMQHk2OpEX3PmwnF+AQAubpUYTHl+Z2EfDkHiIIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pxc3l7nck3ku25nd66f5ul0c0gkhtnjmnr3zk0ftmm2yt3qn0q8strdzdy
    lastmodified: "2026-07-03T13:58:00Z"
    mac: ENC[AES256_GCM,data:gO9X4pD+yVX9xj0w23wnOznPe1Uh7ld3tpIEdNCb8iuekYCeWXgN0METC8e1NzIBHN+4z7eq3rc2YWsHH7dOo33G3R1d9Wh3T0upOBNC87hSCS0vQbB1ZsNNZoVX7lIxCcM9+rIuALddJbchtms/ENBjhB+STG9VYAjhNQj+PFI=,iv:cKeaZJutYJtftdNxgJu8COC4iujuR6qgGitwmf+dA8A=,tag:UTIIzxVoM4G2y2HRUBPpKw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
