#ENC[AES256_GCM,data:pP7SQDxcWGrLtGutHsUkbaJgf0F5+SmcWyWTx+fb1O5htiAevhUiP/mm16bjd+3dhx7a8emiNHIRMaJn28doiTglKDGgTw==,iv:82khWk7nSvHH0bcVLOrTORsvzdsc6tyW8L2FaUQ+8eU=,tag:6+mWHhnuDu9FZ7hw0I7Icw==,type:comment]
#ENC[AES256_GCM,data:1+SzBbhlSz+cAtMgT1wAGNzKgbw3b+64Yvxp2FGhz2uKxqfsl7hfjZ713PaDaVdEf7xdDJ6EQnM/sjQsy4SuP9FqJKF04O3I4zizgs4=,iv:jhFm3+fWfQNyKmjv/AdxQQSjFNiXYm9f6ta7srMXPeM=,tag:+kv1mEeCtr2ObdLP0250/w==,type:comment]
#ENC[AES256_GCM,data:hybCL1VK/WaIkCfEV4CwObMLLrLbHHANRZfnvmQirF7JelLar3pCTQx+mMdrrEDI8uVpqrbAihzepUbTyNbdW8SCsJqOhlA=,iv:8l3h+21QqjIhQLtv5c7SyoFWg47zZXrW05QXFVlaeII=,tag:TYZUnvyExFdjt7QVV6zF9g==,type:comment]
#ENC[AES256_GCM,data:Fq9pbibEx6mhkYyabLgdZEtzHl3fmH6NLQUlXIznQlDJAUT1OxkVWlML4aMtbu7y+KJehwBEbZEHUdOfSzcEwvzL4We/A3+witjQ,iv:b64+CyothAE09QcXEUjdNRDsnPP1+ONOGm+8JuH2TGw=,tag:7uydCgNPA7PS2gKlsOjsyw==,type:comment]
#ENC[AES256_GCM,data:9cvcBfC+MDR9szJ1mIO+9gVtuTt8W74=,iv:aI9tfXKfY7ebgJIkV5MIILGwaO3vFz9BOiY6SjeZOlQ=,tag:U1tT1w1KsyPdrLCm6DOeYA==,type:comment]
apiVersion: ENC[AES256_GCM,data:i6Q=,iv:AFeIfbh//sGoBSoC+rOtkXCZJj3OQgDVWZRnrclkI+M=,tag:zoXoTTK+SCsRR/gJgoLNFQ==,type:str]
kind: ENC[AES256_GCM,data:ROgF9wTt,iv:nawJPCci2gHXrmHN4e93R8+AqBsuvb8FevQAnoIG98s=,tag:1pkRUcNaUypguQrKIztV+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1dYeykMl7gOiyGweCdysGAXO,iv:l217FEgHJO+FwcS/Hj6X1xHEP+fTfRotb3aTI4LmapI=,tag:dWRrHbrtf/T84W4fFW2z5g==,type:str]
    namespace: ENC[AES256_GCM,data:uqG42/A5p5ezFuneb4k=,iv:OsPzkcU9PN2gCUf0FSfSq/zlWp4SjrWzMNqeiSXMSLI=,tag:t1NV7qk+IKY0UfU1wQePCg==,type:str]
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:pSX07kKe34lfVXi25sqEV0jtfSceZf4vTPG1bNSlmqZAATrfjquVH42M3mmtOlWmmhex4ATHRGcC5vBxEtmqDVO/2fii1M2IcWrpGtI54PbA9QohdXvJB4bsphDbvQM3YlmBTDyh0wHyrwH2RwHkaxE4s3M59LbSbAzCQhikCH25QIuhOjGzGMPmAuXEdjZTf+rXIiw6sd6qiC+Yj/bC7P4KIUx4nvdYbdYuubtcZRu/JR3UiOCLgcj7a9w1jV3Y53KBvoU+pZJwO9GPgcSvN3wW8h4IjPRV1TJ/HFVvAP7371PTuncDgKX2BpNUrGd4r0eo0PI4OJw7iKaTKedHVvYhBP5biHRr+NoJ6JpT8q1oWoK2l9OLigQABMCZg4OyCxKtYGBn1FTRSbSpCLHpZeLVDcvRkTF9iO5k31PgQT5JOruZA1GhIUqPiR59c1fzb7++xNA53/O4w4vQySJ03oqF5NEersb7VhjfHwj0j1quAR+KNGca4V9oAUfM2I2Hw9sAFWpDa+UeXyN072NTGyIKDuxSwN22EBf4lPuJwiquFtb8F+W1qqqVL5GgmR7z7jXmp0kpUOyTLDibBbcosG273CwRfbevyQzYcP2WpqL0Xvqb8BgnhmfMmp+Uq5D8OEylfOieNLbbjwL2WoejB+brMZKED3Kcxv72bFLzv1EmyHrs382QwEn2eVoEUoDXhvjuwUbmoKjgZUAM+z1GxdnPmtPL+YaNfzRovYEAEuENs8t3XVtkNYZICKw7m2yynLan05cg9kWr,iv:3lAN9XUTcYt44h3tFBf45PwAuXmksIB/4YPnR+EiyC8=,tag:MUW55rwz1jOjUPiP39mHbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKREpmeHlNNW1TZEdsK2tu
            My9RZFZtdXRlK1MxV1QzU1owQ3RKa2VYbWpzCi9sUVBrYWdpOURUdVpmMlJBeUFI
            WEZGVmpBWW9VcVFobkZtbWJHeklJdlEKLS0tIEgyV2l1aU01TUFmS1lvMStDL0o3
            c0p0cnMxUTU3VEhQR1ZmZlJBeEwrODQKiaN1yk+NTRyT6Vel2HdjlQ3wycsCfsny
            FNIPYPY8seJtpmE8t/vlMtc3m4XPBJMkFww9m7AJo6a6qdXqA5Hflg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl0nmje9vetdgudflgcnnydcg44kv9a5px4e8lhyaz3qfqewjfhqhdg5ra
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMHVlbzJsUlFHS0xqTEwv
            TTNseXJNNGhBN1hkMW96WUhjNUFpTk9tMUFBClRzQlNnY1ZVV09wRmRESG4rcFlw
            OTZxTU1WWG1YU2I1TWorQlpmWVhJbjgKLS0tIHNMT3NUVjA3cm9UVFE4SnpIVzA4
            cjc1dGt0cVliL2dHb01zQmt6SDJheTQKwQo0YyCAKelSmTxv41j2AtPIBxRLbSK/
            BmJnMW9cSTAS2AF1n3zyULWK5JM+kt37ZEVWLwjAiXbBNb27oa55cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pxc3l7nck3ku25nd66f5ul0c0gkhtnjmnr3zk0ftmm2yt3qn0q8strdzdy
    lastmodified: "2026-07-03T12:18:18Z"
    mac: ENC[AES256_GCM,data:nr9vaAdibKgSg+JwRFexDxDrb0kPntBnev5Bo6LbR+SwTY2uYXhaOp41ZAWA8eF1WqPk3l/iUCPabCjHpAANPhyTKTWt8qZHf9vDi/tE2u6w/HOmmHS7utJaa7LxLeCTvvkj/ztg9wwnrw7yRNMgVRhTbFJxSRjd9tOwBUqEPos=,iv:Vt2fQI8ZrJ2Nh7SY5ct+p8w/WEzIM0iysmAyjKI+56Q=,tag:Ri8ZjbYu5FVThCI0JyYZmQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
