#ENC[AES256_GCM,data:b2/UdMeoZ/LZQq1XWZtzvyHj38YA47/b4qQw1NYEb7klPTimsFcwZ75VfO0KjzIBJW+iwBwSKPeZ8Wgz+877nb3p5lIlfw==,iv:sPF45Zjhxt3ucdcfDGKpe0kmnlWZKtwmGKuramL9Rro=,tag:nT0R4QgGdYTJ58Plnpa7RQ==,type:comment]
#ENC[AES256_GCM,data:UfybE22qlFLCLNoS5w2cgKvx8iTBz5vX93QYzN+tJJaNzpnLdzKVvJVP+UdTpG5Qvn5mn4yi3SHlcQoPlhKLm7WZbW3HQKo=,iv:Ysu8GnRXTGTgPyURwRws81b5ZJPQX3fqJcltmMvyDxg=,tag:bC9rR2AWUabBeOCNzUAvAw==,type:comment]
#ENC[AES256_GCM,data:lgZZXIKbmo8+peAF2ebolO59WngrgCe1Ur6wVrCYD8GBIAzGa6jItvHsbOCmgg369jIBJtUj48fukaSzUVM+wIKyv3CN/A5uC362fW4=,iv:AR8F7/0GFRVYuFR6o2XhGb0A+p4syKsbx4Un7vmPhh4=,tag:u0lB7xRjbq5Z4ioBpYaVqA==,type:comment]
#ENC[AES256_GCM,data:qo0oBzNUDR0Vme92jE4ULOJHGt0DHnz8Ppv2hsxQjJrdPcRpcrXTdRdfuTgD+paYJNuWxh4XBdWoFAXNgxIwSAVANwqxIp7hfg==,iv:nkH/ZZcLEy2DknNPIDkKi/+rvmjUs+NGkPmNDBUcl1w=,tag:t1Ua7Wvj0veMMOxTkwJNEw==,type:comment]
#ENC[AES256_GCM,data:Sb+fKoBPZStIJpKINqX8pKYWN3bQ/HbCNCtgoaOiBlfqAGjmTAlFCzefbl235YuM0P2l6HNrsvTkqamapI8ojIOnShE4,iv:i79Brn1IFt7enoTyzV9+OTrPw8Yvq+6Ud1ey7rdGMUM=,tag:EGFXevLyQ4RoUlzXfPuHlA==,type:comment]
#ENC[AES256_GCM,data:Lb54F+I8ZW55xUlgoxvX,iv:VtRQcIqHAsA8LeBHj8NwphdWBnmt+D/8BwEgui/u/KA=,tag:PuA1TqRPmdjTJqZqnmNzYw==,type:comment]
apiVersion: ENC[AES256_GCM,data:Zjg=,iv:UqpdhSbh8zHSz5NBUVKcQNPmzIY6j6v0+NrwpMZm9fw=,tag:gpgW7i3PdSJpg9O6YZrbyw==,type:str]
kind: ENC[AES256_GCM,data:eSp+s7SK,iv:Mo99LTHiwRUzgbpmrJhtcoLyz2K3yQXiBZJ3im251xs=,tag:barp6jVz/Xo2kv9dnG39Qg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zQhI2acZkA95WUcvqYPI+LO4,iv:Ta2JYDJaCB9mqvIwqbxg2KwdfpUWX/XDIJp4bBWWRGU=,tag:vvjMmo4RMn2Gp4HKfqkw5g==,type:str]
    namespace: ENC[AES256_GCM,data:CAG8XCq52JXab0ZrNEE=,iv:grodTKfj8WJdTMd184Gt01VPnEvZ+JATzlErgwe91Nk=,tag:D1zfqjkdTjr7o7o2pFQuvQ==,type:str]
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:1QfO4H/R3yIYlBmIN9cB7ZVnbRDyGTutXPlgixi4T+iqixcaVxZFGggUJWskgn/0OnngoCYo5RW3NdK71bYQQgQH4pfe6YM3Cq4ozQdsOw9Vddpt3bon691B/irlwrVK9yoXpUOXsIZp1+gwIZ2hksRNiixLuXU4XdLW5p4NEqDzio7yXigqW5TyHkC1bfAQUo4qyD4RKene5iAYu5hP/9wXEPzk1KVLdN4BFq8PBsTjTpNSL+haYW5Oq79nIkJMO8AnAIqqaEKZWhj460Dsr4lUxdWmApSNQKLXLbWAeCi/QsC9dt4pFOOdZWUD0M9GDekcm1UkPJVdmQOMbBu6xmMQ/a9bVqPLxlhOh0eFGKaO8+5JrtJq9mVi7YcqznDRItAKDOMaMeRYGqaXOKuJXPhkwIlD7Y+yskLhT0msvkM0I2VhNMd5jW8N+qcWRBRqqH9Vs03SPtXOUUXy6oRcRQb4pU7rtmNyXoef2MDX6H8F/cuj/B1/CJWn8qZ+upKa9YGWz8w78goLwQCXi1NNxs0v8qGXSgiimid5cy+X7mhKsdwkTCj7lPJ1oerif4F0CjnoVurOQQEVuQHROx8lF0+t4z2UjIE7Uz3PwIAzhGNtZK1/w3nPIZQWGjdHBnr0L1CHQnJcP6/gL6DNq7JKjDry5VVdof5NLQZmXw6uWhlR03mu+HvDtotxjpD+aHRw8SFFCka+3aElDU2aiAlX1DcX6I8E2IfLP5+0JFWWMGDBZaDwvSSRT2a7kbKF2ZaT7UTUnaFmzA==,iv:HFJllEeoPtG7jlBhDovK1YziI+hm06jfmXYY9Str8j4=,tag:nsOEgcdo6Ss7Xun+cYI5Jw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSHJ6QVZ3WUU2cGcrQlBF
            OVM4ditvOHZiNE9ubzIwaWNPRU5ueTFFd1hBCnlaeEpvUW9EQlB5UUFaTlQ0UXBr
            UlpoQWZ4dHM4cHdWU0tmdENHeklVREEKLS0tIER3MTRrMHBRcWovTWxHZVpoYVg4
            dlUxcG56TmN3NGtYVUQ1YjRTSEZIWHcKCF+0a56kJFgRzHNyPtYpsRAOOur46RYe
            h1gTCmxNsksWtqDhNZXhmzPpsdmQYWHgYt2zuDaD20MzvOYxbgWYNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl0nmje9vetdgudflgcnnydcg44kv9a5px4e8lhyaz3qfqewjfhqhdg5ra
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RWh6V1grTEFlSmJEN0hP
            RE8yRmU1U2FHMm83Rnc1R3NXa3BOanF6THg0ClZISGNHOC8zV3JNbmRFY3djclhW
            Zm5zU2t5N2ZhYzRZTXQ5bStVZWNEL3cKLS0tIDBESzhhSlVUaGFjVXlaN3ZJeEFX
            WTNwSEJ2Z1M3TUJlaUg0bnRNQ0FPdmcKz7JtB+2Df/R12UNMqcu1LiYyXStJdVml
            LK7gbkohs3KsGiqG72ZcnwoSLtJm2mKPXvMXENDHf9C+b2OQLO2nAg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pxc3l7nck3ku25nd66f5ul0c0gkhtnjmnr3zk0ftmm2yt3qn0q8strdzdy
    lastmodified: "2026-07-03T16:45:07Z"
    mac: ENC[AES256_GCM,data:J+N2KOM3xmIIXxdvScy4kqGn5W0NnsuxA/OYI/HL1PjmLKM9IUQHiwV1CpsARsUDVcudO+It9J4ketYury7DahE5ZHt8ZBbQRd5s082/o9vLbNpeyenKvMXPJk2fVjnaBZoCaRXtfO+QGXdyxFEpTDhAHySxStEXfND5sBFt4qk=,iv:VuL8A/COLGMxIwymkeG28FMU+L8GEne8XflOuZYrPPU=,tag:7XgR14G9z65dgO3PwKJefQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
