#ENC[AES256_GCM,data:fI9rv0b1UJTZGsrpdUi1k2ptXEDubq1ACRUc3mE0hmYJb7bbJII7JMg9weaInJf7OaKAiyn87Iz02tdBI8rujcIvbSlvkW6R,iv:TKo87VH88lxnKDZnYQODizG6ZMnIWO/lpquM1SDSnoc=,tag:fiAjmMHHax0MDWhn855a6A==,type:comment]
#ENC[AES256_GCM,data:AlIYs7tg2UR0Z0Zxoxc1aPdxQ1AJVDTRLYW/q/toaGuhwc94KrzeVWgYoQcgx2mkrNUUMvszduoX0qfb1DEJkNkD0D3BCiBIMz7QUUM=,iv:0aKRB2oJzHq6CDQeWjsT44z/GueYCor/Vw8YmZNzrbk=,tag:ij3HWIXWL3P+1T1pyXM+Mg==,type:comment]
#ENC[AES256_GCM,data:XkV7uw/Mw7G18JQyIiwN1338oN/Z4jXTS3qu18rdVQF7GllrX2aFvEm6PylSIiw99nFhQ0m/FLqEa5ipf/ltIj0O75/oJWZJP59qCA==,iv:QToCTbtZ6vl9XIAy1K3P+wv4Qil1idc9k8nZfJFlf4M=,tag:dbo5SSRUL71XR0c0RSnJPw==,type:comment]
#ENC[AES256_GCM,data:eZtidqHk5SsyjpsL4m3qm7VhlxjVRtyswvYa9dcPUlcZiJY8OBd4NYtvjywnee2TdJKVIqtiRheUy68MkXbjhQFB3a95J6LLnMSMt2txsQ==,iv:MACN/NV7DX34O7n4AHdWcKVTMRys7ngalMHbd/4JbU8=,tag:ifOGXq+dWBS1SsZ3T/Um6A==,type:comment]
#ENC[AES256_GCM,data:mw0sraRMeq3ypd4RxV6T0lpVcTI1XHtjbGqPryHjqx2K8A/WJzh2bzjqN/Q=,iv:a8u7bQiWl02FaPCAnOgIA/U/TGzI8MW7yuS3Aa0Oi2U=,tag:G5+3CUN+ZhpxCQgRqPmNRQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:5Sk=,iv:IPmgTn/WSX2y+wU58hmgUtRtQGXf0SHzru6QqZ/Q72M=,tag:bjU6fmttAbd9T0vFNGOv1g==,type:str]
kind: ENC[AES256_GCM,data:RSGZ3+Ku,iv:qPtU2weiogjX/VGk9aP4Cl1W7Q23v9ThzhBA+fU01X0=,tag:SsxiDOxRU9JxTKB0UMR1bA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3hkj+ybbHsOyUmKEA89dUs10w58=,iv:hVSSnZUy83cx0/fnA3TUiX7ILWTDJdB8vot3yTCh3nY=,tag:oGOCodOxCNPydaj/E/KN8A==,type:str]
    namespace: ENC[AES256_GCM,data:4jX6dz9DFjsBkBYphAY=,iv:eyegMuPMeppud14fiuUqgVfQr6bNZ8zIbVJjmxxaaY4=,tag:48B/Pmm5OnDB/I3ac0rzWQ==,type:str]
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:l+yd/+3bZpF+Jut59V3EmH8FAOL8M2BJ54Z0GremqqDnSC+qxik2MncFOpP1kNIrFPvXusN2V/pNYvWoZtkgZm0RjflfCsb//6vFNPKmf2/AouksFMUip4uarEseJyQwmubS0cY9UR9BGzJrgoZEDBO5CI8+1q+CM4+9QK7hTvhHEGUUkuev4jgIG7l2lVi0BFXMix0kzYIdLXpn5926dMKBj8F+0/eU7r1Ck9U6g7WtKKn1EB1wom0bIvsALk28oKa21PaZDTVwXWYXB69akLtwEn9SJKe6mBNvTj5BKZHZWBaDGGFSpvNkgFb+tx3P2kbIhCRlE2CYT7lAgZwhs6VsdtcA/LmoS9ECrvhV3yxY9wsBNzhqRakiwdV2oMACs7K4SmSCrV4UssGlLNNEgu+//KvdXYtzZpazU/R7JVOJv2eJD8ldlNskJcixx3tDOUah+a/8DzmsSbI9He/midQbp6ZH13B+jscc3VfLb3YUI4ol3QsWSrg7Eo6raXpiZlS7+z6i6ApHJTRnefKSTfP12l4Y/zzlO8vikS3ghMCWiixJhBHpF5Ss9fWdrhsKR8W0Mjz6WoOemzDEcYrbfCt6fKg26jeHGyIFKuozwy2zRDbwRkYTukIM+xy+4U3Ql5U7IvByzL5vxsoxVmY71y5hIdml/YW/DRcG0G2Dg8x32vSjKTtXTcOOlfkulvnI9/MRVBAS+iDHv7SOc1dO55CaKKpd+x2QwVtnhz2Jy4p2HvRnHZfzSY7UKJVpRLx5qPnSed1ZLcq7jGw/6t8I3gCIc+EFD2R2FLE9FChE4oG+mUExT2DEH4geAs1Civ756LC/kdd9kLxlCGiMHx593/dk0OQcLIBi50xI0W251iRJ/Eu+xXbpX69Gv2SmRR67Dg+HOqs6efDbGIkel1blMyk7LNrzcyGwcvWsnwuC3aAwQ36dMEYIMJoGB8HHfNLadzLfHysVw1SnA9cn+NJudQ==,iv:wqvwkd9ewXdkLOrYDmdHUee2/Xm9ytaqM0+SC8GqsFc=,tag:BxLf97tWgRhVL2tN4vBIxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrK2lJWnppTXZPQXBvcmcr
            MFV5ZndnSGh2REhZT2RnYm1RbEUzdWcybFhJCnpIejZOVXlMYmZoQTBJNmpNUVFx
            b0tUWGhveUtHN1NEd0ZYTTFuU2k3UTQKLS0tIFhsUGo0ajdhTkZPYnZwV2p5MFVH
            RUp3c0JCd0hDM041elYrVTdSWHJxZXcKAyxCtfkpK3T9nLHl5Kah356gGFR1b8iw
            0J8kFtOfHBQOHD0hozWbDybj/wa9MAXcdX7mIzeqBygAU5hWqIfS3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl0nmje9vetdgudflgcnnydcg44kv9a5px4e8lhyaz3qfqewjfhqhdg5ra
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlLzhyUjFrcGJVZk5uKzNz
            V3pPbVBJMEFFakJPemd5blZrS0VycUt6eW5FCjNoQUp5SldCM3l5YzlXN2dRWFFE
            M00xK0cxT1NwT0dobkxaemRCNi9yZ1kKLS0tIDA2NDM1eHBLR1VYNkF6VSszMUZs
            WEl2NTlic1k1eUFteUpkenVhOUNNeEUK3fleoCedAGAX6duICm9dYMyxgrKuSrU1
            QTT8UuSt3OZn5KPMQHk2OpEX3PmwnF+AQAubpUYTHl+Z2EfDkHiIIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pxc3l7nck3ku25nd66f5ul0c0gkhtnjmnr3zk0ftmm2yt3qn0q8strdzdy
    lastmodified: "2026-07-03T12:18:18Z"
    mac: ENC[AES256_GCM,data:6r0RXTyS0JoJlhTFfyE4kc07d1RlbjpnncX213RoMGjOqEdGQm/izuul7Ks75VBrnUQa28+KxCi9Sdzo4BoCL98Qf14IFlCM/xsATK/FVvs+PzPcSPvSwhntCD4EfK8Wm5rFSBtrsMAJrpwjio6dg0BqvSR7OvDIPWkBcxWRzn4=,iv:DrwyGM5M/LEyJcOFx0oSvQRJPZRG5iLHCgITARtJNeE=,tag:URry8No6C3IUvoegFcGIVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
