#ENC[AES256_GCM,data:fI9rv0b1UJTZGsrpdUi1k2ptXEDubq1ACRUc3mE0hmYJb7bbJII7JMg9weaInJf7OaKAiyn87Iz02tdBI8rujcIvbSlvkW6R,iv:TKo87VH88lxnKDZnYQODizG6ZMnIWO/lpquM1SDSnoc=,tag:fiAjmMHHax0MDWhn855a6A==,type:comment]
#ENC[AES256_GCM,data:AlIYs7tg2UR0Z0Zxoxc1aPdxQ1AJVDTRLYW/q/toaGuhwc94KrzeVWgYoQcgx2mkrNUUMvszduoX0qfb1DEJkNkD0D3BCiBIMz7QUUM=,iv:0aKRB2oJzHq6CDQeWjsT44z/GueYCor/Vw8YmZNzrbk=,tag:ij3HWIXWL3P+1T1pyXM+Mg==,type:comment]
#ENC[AES256_GCM,data:XkV7uw/Mw7G18JQyIiwN1338oN/Z4jXTS3qu18rdVQF7GllrX2aFvEm6PylSIiw99nFhQ0m/FLqEa5ipf/ltIj0O75/oJWZJP59qCA==,iv:QToCTbtZ6vl9XIAy1K3P+wv4Qil1idc9k8nZfJFlf4M=,tag:dbo5SSRUL71XR0c0RSnJPw==,type:comment]
#ENC[AES256_GCM,data:eZtidqHk5SsyjpsL4m3qm7VhlxjVRtyswvYa9dcPUlcZiJY8OBd4NYtvjywnee2TdJKVIqtiRheUy68MkXbjhQFB3a95J6LLnMSMt2txsQ==,iv:MACN/NV7DX34O7n4AHdWcKVTMRys7ngalMHbd/4JbU8=,tag:ifOGXq+dWBS1SsZ3T/Um6A==,type:comment]
#ENC[AES256_GCM,data:mw0sraRMeq3ypd4RxV6T0lpVcTI1XHtjbGqPryHjqx2K8A/WJzh2bzjqN/Q=,iv:a8u7bQiWl02FaPCAnOgIA/U/TGzI8MW7yuS3Aa0Oi2U=,tag:G5+3CUN+ZhpxCQgRqPmNRQ==,type:comment]
apiVersion: ENC[AES256_GCM,data:5Sk=,iv:IPmgTn/WSX2y+wU58hmgUtRtQGXf0SHzru6QqZ/Q72M=,tag:bjU6fmttAbd9T0vFNGOv1g==,type:str]
kind: ENC[AES256_GCM,data:RSGZ3+Ku,iv:qPtU2weiogjX/VGk9aP4Cl1W7Q23v9ThzhBA+fU01X0=,tag:SsxiDOxRU9JxTKB0UMR1bA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3hkj+ybbHsOyUmKEA89dUs10w58=,iv:hVSSnZUy83cx0/fnA3TUiX7ILWTDJdB8vot3yTCh3nY=,tag:oGOCodOxCNPydaj/E/KN8A==,type:str]
    namespace: ENC[AES256_GCM,data:4jX6dz9DFjsBkBYphAY=,iv:eyegMuPMeppud14fiuUqgVfQr6bNZ8zIbVJjmxxaaY4=,tag:48B/Pmm5OnDB/I3ac0rzWQ==,type:str]
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:sGBaK/fPQnlHXkzqz/gapFPOoUjZ3/PmX1GGmy/O8vyvNwFwx9OwXGUDQzuj+527TJzT5OILF7TEUVH0ZP6UyFCftr8RbR3Ha6mOjyb7rweOHW9Dg66C/HansYrwEeXgoeshxGTP+DqWZ8MFSYETzwGZYpQBRSHcJsXmfwNx3ESrZc2up1GtyG1UsfcmbWgJKV6P1CbhcT/+6NMz3wV7jTGNet0xUP1ysljtIguJNDxkTylHmOexaMCAvwAsRaarmmPlss6FKu065gdnvLKKunxSkB7DTYtHNojOfWdCGTAt53pLQaCgmo8AuQtulxf1aHgLgFR1zFXpHJJ2Is5N78GQxEMBJiu7FW5v5noZMZf8YE8hxtrBnry1OUnQ3Mqh/fJlZ1UZRymC263oG4ayQ23xJmf2ng38rwtHd4vkhMkVBU0BFhM0aWrpXIqbGf0REtqkpH9KxbcCe0Cv8CkVYzru7jtN8iKiivDiG3jVEgdYuIw7rzzONHHCRvkPNWq+pTGJ2OsKrSmfIZRkxaL+pRJSb0n8/tIWmM3TIm5fOZTNUGRxwTgHQ2HT+zZCnb4SjydmM+QolVZUL+XaHy1gJsQip0jD4Xn6zz8/zCk8k5K9TqSKE1R15CB7Gpot/dLndneghr5JHPM4SM1PWcZfYmjK45NekTTizlBpeMvCOVaA1qYd2pZ524lDRXKJE1vy03rPh21iw0fm2FQOk7Yx17Fm+zbjSZQFK/LesezPx9T3/q2S5UPNNhon00NZI/wwMQO5MX0xnWIXnOXZrKGJmZKsYf7Q6qAn8I2qWRYl1uX938eNi8LgDq7i/tJCcF7Y/uosfRYzmhANsw9AZCUdkcTO4jRBtdunnD2cDTP1gbp+CZ9uaTNXsUYQWthyAgKFf2ruouYrCy2qi/lkEro24XZsp2SBbsqqr1SxrtSEfQe6o0ZWzqegznJsGXRaExcm8mx/rrEWvIVBSmcBDcOq,iv:eYOIyIo5N9Wsqm0rjzxRhjpLOLMVS8Ip76FUjf3bdEE=,tag:lsFI2oN6TsmunXV7gPPY2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrK2lJWnppTXZPQXBvcmcr
            MFV5ZndnSGh2REhZT2RnYm1RbEUzdWcybFhJCnpIejZOVXlMYmZoQTBJNmpNUVFx
            b0tUWGhveUtHN1NEd0ZYTTFuU2k3UTQKLS0tIFhsUGo0ajdhTkZPYnZwV2p5MFVH
            RUp3c0JCd0hDM041elYrVTdSWHJxZXcKAyxCtfkpK3T9nLHl5Kah356gGFR1b8iw
            0J8kFtOfHBQOHD0hozWbDybj/wa9MAXcdX7mIzeqBygAU5hWqIfS3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl0nmje9vetdgudflgcnnydcg44kv9a5px4e8lhyaz3qfqewjfhqhdg5ra
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlLzhyUjFrcGJVZk5uKzNz
            V3pPbVBJMEFFakJPemd5blZrS0VycUt6eW5FCjNoQUp5SldCM3l5YzlXN2dRWFFE
            M00xK0cxT1NwT0dobkxaemRCNi9yZ1kKLS0tIDA2NDM1eHBLR1VYNkF6VSszMUZs
            WEl2NTlic1k1eUFteUpkenVhOUNNeEUK3fleoCedAGAX6duICm9dYMyxgrKuSrU1
            QTT8UuSt3OZn5KPMQHk2OpEX3PmwnF+AQAubpUYTHl+Z2EfDkHiIIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pxc3l7nck3ku25nd66f5ul0c0gkhtnjmnr3zk0ftmm2yt3qn0q8strdzdy
    lastmodified: "2026-07-03T16:28:41Z"
    mac: ENC[AES256_GCM,data:qJ+l76odT+aEy/wnwiuwRQCsIorSeenmIZRK8N/+jwVB99AsNmXIiSVFYgHK3xitEtFU/jURbysEKRnAL2jspn2Qxnyj0dkC4H2NCB4J2lMTyzUWbnLZBzq9vUscw/rHd6QsaZdK4Xtqmsoz2ZqvUDoorY3F095ndvATmKxZx20=,iv:TkZBziqn2W65qj64IpgSn8lnH3+P3TVhjk8R2DSuANc=,tag:ujqemUX3JE8OaXF63Nmi2g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
