apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: truenas-driver-config-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./driver-config-iscsi.enc.yaml
  - ./driver-config-nfs.enc.yaml
